@server = http://localhost:4004
@auth = Authorization: Basic alice:


### Books
# @name Books_GET
GET {{server}}/odata/v4/catalog/Books
{{auth}}

###
# @name Books_POST
POST {{server}}/odata/v4/catalog/Books
Content-Type: application/json
{{auth}}

{
  "ID": 201,
  "title": "New Book",
  "stock": 100
}