name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug permissions
      run: |
        ls -l
        whoami
        echo "Checking working directory permissions"
        ls -l /home/runner/work/github-action-piper/github-action-piper

    - name: Build
      uses: SAP/project-piper-action@main
      with:
        step-name: mtaBuild