name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add permissions
      run: sudo chown -R $USER:$USER .

    - name: Build
      uses: SAP/project-piper-action@main
      with:
        step-name: mtaBuild